[workspace]
members = ["modules/cjls", "modules/calca", "modules/lsp"]
build-members = []
test-members = []
compile-option = ""
override-compile-option = ""
link-option = ""
target-dir = ""
script-dir = ""

[dependencies]
