[workspace]
members = [
  "modules/cjls",
  "modules/cjls_db",
  "modules/calca",
  "modules/cjls_interface",
  "modules/lsp",
]
build-members = []
test-members = []
compile-option = ""
override-compile-option = ""
link-option = ""
target-dir = ""
script-dir = ""

[dependencies]
