[package]
  cjc-version = "1.1.0"
  name = "cjls"
  organization = ""
  description = "nothing here"
  version = "1.0.0"
  target-dir = ""
  script-dir = ""
  output-type = "executable"
  compile-option = ""
  override-compile-option = ""
  link-option = ""
  [package.package-configuration]

[dependencies]

[target]
  [target.x86_64-unknown-linux-gnu]
    [target.x86_64-unknown-linux-gnu.bin-dependencies]
      path-option = [ "./third_party/stdx" ]
