[package]
cjc-version = "1.1.0"
name = "cjls_db"
organization = ""
description = "nothing here"
version = "0.0.0"
target-dir = ""
script-dir = ""
output-type = "static"
compile-option = ""
override-compile-option = ""
link-option = ""
package-configuration = {}

[dependencies]
